version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock-visualizer-image
    container_name: stock-visualizer-container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1